version: "3.8"
services:
  app:
    build: .
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8030"]
    volumes:
      - .:/app
    ports:
      - "8030:8000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
